### PR TITLE
Update mapper script location to Mudlet repository

### PR DESCRIPTION
**Pull request by vadi2**
#### Brief overview of PR changes/additions
Update mapper script location to Mudlet repository
#### Motivation for adding to Mudlet
So `map update` can migrate over to the script from the Mudlet repository
#### Other info (issues closed, discussion etc)
There's a lot of changes because your `development` branch hasn't been synced with Mudlets in a while, so the changes are OK.

### CODE REVIEW

**Comment by vadi2** [comment]
@keneanung could you double-check that this is OK?

**Comment by keneanung** [comment]
Looks good to me!

**Comment by vadi2** [comment]
@JorMox mind merging this?

**Comment by vadi2** [comment]
Thx!

**Pull request merged**
